### ISSUE TITLE
Error - admin Execute fails first time

### ISSUE THREAD

**Issue by urirot** [CodeForPhilly/paws-data-pipeline#372]
When running execute the first time, it fails with the following error:
```
[2021-06-18 07:39:28,983] INFO in admin_api: Execute flow
127.0.0.1 - - [18/Jun/2021 07:39:29] "POST /api/execute HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/uri/PycharmProjects/paws-data-pipeline/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/home/uri/PycharmProjects/paws-data-pipeline/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "execution_status" does not exist
LINE 1: SELECT job_id from execution_status
                          ^
```

**Comment by c-simpson** [comment]
What's the value in the `alembic_version` table?  It should be `bfb1262d3195` . If not, check server startup logs.

**Comment by urirot** [comment]
that's the value I have

**Comment by c-simpson** [comment]
Can you confirm you get no errors when this runs at server start up? 

```
paws-compose-server | WAKING
paws-compose-server | INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
paws-compose-server | INFO  [alembic.runtime.migration] Will assume transactional DDL.
paws-compose-server | INFO  [alembic.runtime.migration] Running upgrade  -> 783cabf889d9, inital schema setup
paws-compose-server | INFO  [alembic.runtime.migration] Running upgrade 783cabf889d9 -> 72d50d531bd5, Fix pdp_users timestamp
paws-compose-server | INFO  [alembic.runtime.migration] Running upgrade 72d50d531bd5 -> 41da831646e4, pdp_users.role FK from roles
paws-compose-server | INFO  [alembic.runtime.migration] Running upgrade 41da831646e4 -> f3d30db17bed, Change pdp_users.password to bytea
paws-compose-server | INFO  [alembic.runtime.migration] Running upgrade f3d30db17bed -> 7138d52f92d6, add uniqueness constraints
paws-compose-server | INFO  [alembic.runtime.migration] Running upgrade 7138d52f92d6 -> 36c4ecbfd11a, Add pdp_users full_name
paws-compose-server | INFO  [alembic.runtime.migration] Running upgrade 36c4ecbfd11a -> 6b8cf99be000, Add user journal table
paws-compose-server | INFO  [alembic.runtime.migration] Running upgrade 6b8cf99be000 -> 05e0693f8cbb, key/value table
paws-compose-server | INFO  [alembic.runtime.migration] Running upgrade 05e0693f8cbb -> bfb1262d3195, create execution status table
paws-compose-server | DB SETUP
```

You can see at the end where that table gets created
